#!/usr/bin/env python
"""
Generate phone-sized companions for every photographic asset.

Why this exists
---------------
The site is a static export (`output: export` + `images.unoptimized`), so there
is no Next image optimiser in front of /public. Source photos are 1400x1800 and
1600x900, and without this step a phone downloads the full-resolution file for
every slot on the page.

`srcset` + `sizes` alone does NOT solve it: at the ~2.6x DPR a modern Android
reports, the browser resolves a 412px-wide slot to ~1071 device pixels and picks
the large file anyway. The only thing that reliably switches on *device class*
is an explicit `media` query, so this writes a second file and Media.jsx serves
it through `<picture><source media="(max-width: 768px)">`.

Output
------
  public/images/**/<name>.webp      (untouched source)
  public/images/**/<name>-sm.webp   (generated, width <= MAX_W)
  lib/imageVariants.js              (generated manifest)

The manifest is what keeps this safe. Media.jsx emits the `<source>` only for
paths listed there, because a `<source>` that 404s does NOT fall back to the
`<img>` — it breaks the slot. So an asset added later without re-running this
script simply serves full-size on mobile instead of disappearing.

Re-run after adding or replacing any image:

    python scripts/gen-mobile-images.py

Idempotent: a variant newer than its source is skipped. Pass --force to rebuild.
"""

from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image

# 412 CSS px (Pixel 7) x 2.6 DPR = 1071 device px for a full-bleed image, so
# anything below ~1080 visibly softens the heroes. This is the ceiling, not a
# resize target — narrower sources are copied through untouched.
MAX_W = 1080
QUALITY = 82
SUFFIX = "-sm"

ROOT = Path(__file__).resolve().parent.parent
IMAGES = ROOT / "public" / "images"
MANIFEST = ROOT / "lib" / "imageVariants.js"

# ── brand lockups ────────────────────────────────────────────────────────
# These ship on every single page and were the largest remaining payload after
# the photography: ~593KB of PNG for artwork that never renders above ~150 CSS
# px (lockup) or ~210 CSS px (the preloader mark). Width here is generous —
# roughly 4x the largest CSS size, so they stay crisp past 3x DPR.
#
# `logo-mark` / `logo-wordmark` are consumed by Preloader.jsx as CSS
# `mask-image`, where ONLY the alpha channel is read. Hence alpha_quality=100:
# the mask edge stays bit-exact while the (unused) colour channels compress.
LOGOS = ROOT / "public" / "logos"
LOGO_TARGETS = {
    "logo-lockup.png": 640,
    "logo-lockup-inverse.png": 640,
    "logo-mark.png": 700,
    "logo-wordmark.png": 700,
}


def sources():
    """Every source .webp, excluding the variants this script produces."""
    for p in sorted(IMAGES.rglob("*.webp")):
        if p.stem.endswith(SUFFIX):
            continue
        yield p


def build(force: bool) -> tuple[list[str], int, int]:
    made, skipped, saved_from, saved_to = [], 0, 0, 0

    for src in sources():
        rel = src.relative_to(IMAGES).as_posix()
        out = src.with_name(f"{src.stem}{SUFFIX}.webp")

        with Image.open(src) as im:
            w, h = im.size

            if w <= MAX_W:
                # Already phone-sized. Nothing to gain from a second copy —
                # leave it out of the manifest so it keeps serving one file.
                skipped += 1
                continue

            if out.exists() and not force and out.stat().st_mtime >= src.stat().st_mtime:
                made.append(rel)
                saved_from += src.stat().st_size
                saved_to += out.stat().st_size
                continue

            target_h = round(h * MAX_W / w)
            im.convert("RGBA" if im.mode == "RGBA" else "RGB").resize(
                (MAX_W, target_h), Image.LANCZOS
            ).save(out, "WEBP", quality=QUALITY, method=6)

        made.append(rel)
        saved_from += src.stat().st_size
        saved_to += out.stat().st_size
        print(f"  {w}x{h} -> {MAX_W}x{target_h}  "
              f"{src.stat().st_size // 1024}KB -> {out.stat().st_size // 1024}KB  {rel}")

    if skipped:
        print(f"  ({skipped} already <= {MAX_W}px wide, left alone)")

    return made, saved_from, saved_to


def write_manifest(paths: list[str]) -> None:
    lines = "\n".join(f'  "{p}",' for p in paths)
    MANIFEST.write_text(
        "// GENERATED by scripts/gen-mobile-images.py — do not edit by hand.\n"
        "//\n"
        "// Paths (relative to /public/images) that have a `-sm.webp` companion.\n"
        "// Media.jsx consults this before emitting a <picture><source>, because a\n"
        "// <source> whose file 404s breaks the slot instead of falling back to <img>.\n"
        "\n"
        f"export const MOBILE_VARIANTS = new Set([\n{lines}\n]);\n"
        "\n"
        "/** `home/hero.webp` -> `home/hero-sm.webp`, or null when there is no variant. */\n"
        "export function mobileVariant(src) {\n"
        "  if (!MOBILE_VARIANTS.has(src)) return null;\n"
        '  return src.replace(/\\.webp$/, "-sm.webp");\n'
        "}\n",
        encoding="utf-8",
    )


def build_logos(force: bool) -> tuple[int, int]:
    """PNG lockups -> WebP. Originals are left on disk (favicons still need them)."""
    before = after = 0

    for name, width in LOGO_TARGETS.items():
        src = LOGOS / name
        if not src.exists():
            print(f"  !! missing {src.relative_to(ROOT).as_posix()}")
            continue

        out = src.with_suffix(".webp")
        before += src.stat().st_size

        if out.exists() and not force and out.stat().st_mtime >= src.stat().st_mtime:
            after += out.stat().st_size
            continue

        with Image.open(src) as im:
            im = im.convert("RGBA")
            w, h = im.size
            target = (width, round(h * width / w)) if w > width else (w, h)
            im.resize(target, Image.LANCZOS).save(
                out, "WEBP", quality=90, alpha_quality=100, method=6
            )

        after += out.stat().st_size
        print(f"  {w}x{h} -> {target[0]}x{target[1]}  "
              f"{src.stat().st_size // 1024}KB -> {out.stat().st_size // 1024}KB  {name}")

    return before, after


def main() -> int:
    force = "--force" in sys.argv

    if not IMAGES.is_dir():
        print(f"no image directory at {IMAGES}", file=sys.stderr)
        return 1

    print(f"generating {SUFFIX}.webp variants (max width {MAX_W}px, q{QUALITY})\n")
    made, before, after = build(force)
    write_manifest(made)

    print(f"\n{len(made)} variants -> {MANIFEST.relative_to(ROOT).as_posix()}")
    if before:
        print(f"mobile payload for those slots: "
              f"{before // 1024}KB -> {after // 1024}KB "
              f"({100 - after * 100 // before}% smaller)")

    print("\nbrand lockups (every page):")
    lb, la = build_logos(force)
    if lb:
        print(f"  {lb // 1024}KB -> {la // 1024}KB ({100 - la * 100 // lb}% smaller)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
